### ISSUE TITLE
[README] Add readme

### ISSUE THREAD

**Issue by quentin-dev** [gconfs/website#12]

**Comment by Knackie** [comment]
HI, i want help, can i ?

**Comment by quentin-dev** [comment]
I'm not sure you can really help us out right now, but if you want to create a branch and start working, I won't stop you. The readme needs to be in markdown format and must contain the following information:

- Installation requirements
- Installation instructions
- Steps to run a local version of the website

**Comment by obynio** [comment]
Ooops, forgot it. But basically the steps to have a dev environment are :
* `python -m venv venv`
* `source venv/bin/activate`
* `pip install -r requirements.txt`
* Rename `local_settings.py`, add the CRI & YouTube credentials, use sqlite
* `./migrate.py runserver`
